remote_theme: pages-themes/dinky@v0.2.0
title: William Milisic's Journaling
description: Written account of my readings, learnings, and thoughts.
markdown: kramdown
plugins:
- jekyll-remote-theme 
- jekyll-feed
google_analytics: G-JFRF05Z3HP
