remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 
- jekyll-feed
title: William Milisic's Journaling
description: Written account of my readings, learnings, and thoughts.
google_analytics: G-JFRF05Z3HP
