remote_theme: pages-themes/dinky@v0.2.0
title: Cloud Cloud Dot Dev
description: Written account of my readings, learnings, and thoughts.
markdown: kramdown
plugins:
- jekyll-remote-theme 
- jekyll-feed
