remote_theme: pages-themes/dinky@v0.2.0
title: William Milisic's Musings
description: Written account of my readings, learnings, and thoughts.
markdown: kramdown
google_analytics: G-JFRF05Z3HP
plugins:
- jekyll-remote-theme 
- jekyll-feed